[tool.poetry]
name = "abnamro-assignment"
version = "0.1.0"
description = "Fraud detection experiments with ensemble and deep tabular models"
authors = ["Vahid"]

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
xgboost = "^3.4.0"
catboost = "^1.2.10"
seaborn = "^0.13.2"
scikit-learn = "^1.9.0"
ipykernel = "^7.3.0"
lightgbm = "^4.7.0"
pandas-stubs = "~=3.0.5"
numba = ">=0.60"
imbalanced-learn = "^0.14.2"
shap = "^0.52.0"

lightning = ">=2.5,<2.7"
torchmetrics = ">=1.7,<2"
tabm = "0.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
